site_name: SoundworX

theme:
  name: material
  language: de
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

nav:
  - Home: /
  - Anmelden: register.md
  - Workshops: workshops.md
  # - Dokumentation:
  #   - Einleitung: documentation/index.md
  #   - Ein Thema: documentation/entry.md
  - Projekt & Team: project.md
  - Rechtliches:
    - Impressum: about/imprint.md
    - Lizenz/Urheberrecht: about/license.md
    - Datenschutz: about/gdpr.md

plugins:
  - privacy


extra:
  social_image: assets/og-image.png
  social_description: "Computerbasierte Lichttechnik durch Audio-Software steuern, Licht- und Sound-Enablement, Workshops"
  social_title: "Soundworx"
  generator: false
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/soundworx_light_audio/

repo_url: https://github.com/fuef-festival/soundworx
repo_name: fuef-festival/soundworx
copyright: <p>Ein Projekt des <a href="http://www.festivalfuerfreunde.de/">Festivals für Freunde e.V.</a> gefördert von der DIWA-Förderung, den Beauftragten der Bundesregierung für Kultur und Medien sowie den Kultur- und Kunstministerien der Länder und durch das Ministerium für Wissenschaft, Forschung und Kultur des Landes Brandenburg. Made with Material for MkDocs.</p> <img src="brandenburg.png" />
